### ISSUE TITLE
What to do if I want to run the demo on another architecture?

### ISSUE THREAD

**Issue by iku000888** [skeeto/pure-linux-threads-demo#1]
**_Complete Nube Alert**_

On my machine, make plain-text produces:

nasm -felf64 -g -o threads.o threads.s
ld  -o plain-threads threads.o 
ld: i386:x86-64 architecture of input file `threads.o' is incompatible with i386 output
Makefile:5: recipe for target 'plain-threads' failed
make: **\* [plain-threads] Error 1

Is there any one-stop kind of suggestion for this demo?

**Comment by skeeto** [comment]
It's strictly for x86_64 and will not work on another architecture
without being rewritten. This is why "high level" programming languages,
like C, are so valuable: they execute the same way across different
machines without adjustment. From the linker output, it looks like
you're using 32-bit x86? Since 32-bit x86 is quickly diminishing the
same way 16-bit x86 did 20 years ago, I don't really bother supporting
it anymore. It will soon be a dead architecture.

If you're feeling ambitious, you could try to porting it to 32-bit x86.
Change the "bits 64" at the top to "bits 32", change the system call
numbers (write 4, mmap 90, clone 120, exit 1), change "syscall" to "int
0x80", and switch everything over to 32-bit registers (rax -> eax, rdi
-> edi, etc.).

**Comment by iku000888** [comment]
Wow, thanks for the pointers!
I will try out your suggestions!

**Comment by iku000888** [comment]
Made Pull Request #2
